command /랜덤스폰:
	trigger:
		set {_x} to random integer between 	100 and 1200
		set {_y} to 60
		set {_x} to random integer between 	100 and 1200
		loop 100 times:
			if block at location {_x}, {_y]-1, {_z} is air:
				subtract 1 from {_y}
			else:
				stop loo
		loop 100 times:
			if block at location {_x}, {_y}, {_z} is not air:
				add 1 to {_y}
			else:
				stop loop
		if block at location {_x}, {_y}, {_z} is air:
			teleport player to location {_x}, {_y}, {_z}
		